fix(go): Adjust the precision of the Timestamp values in the JSON-only path (#2965)
After the update to adjust the Timestamp precision, the JSON path (which
is hit when using SHOW commands) was still using nanoseconds even though
the schema was specifying the precision as microseconds, resulting in
downstream C# callers getting the error

```
System.ArgumentOutOfRangeException: Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks.
```

---------

Co-authored-by: David Coe <>